databases:
  - name: beget_db
    databaseName: beget_db
    user: billy

services:
  - type: web
    name: BudgetApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beget_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false