databases:
  - name: recipe_app_iieu
    databaseName: recipe_app_iieu
    user: recipe_app_iieu_user

services:
  - type: web
    name: BudgetApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_app_iieu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false